export const items = [
  {
    id: 0,
    title: "lol1",
    description: "mda mda mda",
    brand: "bmw",
    category: "chacha",
  },
  {
    id: 1,
    title: "lol2",
    description: "mda mda mda2",
    brand: "bmw2",
    category: "chacha",
  },
  {
    id: 2,
    title: "lol3",
    description: "mda mda mda3",
    brand: "bmw3",
    category: "chacha",
  },
  {
    id: 3,
    title: "lol4",
    description: "mda mda mda4",
    brand: "bmw4",
    category: "chacha",
  },
  {
    id: 4,
    title: "lol5",
    description: "mda mda mda5",
    brand: "bmw5",
    category: "chacha",
  },
  {
    id: 5,
    title: "lol6",
    description: "mda mda mda6",
    brand: "bmw6",
    category: "chacha",
  },
  {
    id: 6,
    title: "lol7",
    description: "mda mda mda7",
    brand: "bmw7",
    category: "chacha",
  },
];
